### ISSUE TITLE
Детальные диалоги

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#1]
Нужно подробное описания диалога каждого сценария из README с клавиатурами и ветвлениями от выбора пользователя

**Comment by gerushenka** [comment]
# Сценарии диалога 

## 1. Команда /start

### Диалог:

Бот: Привет! 👋 Добро пожаловать в наш сервис. 

Клавиатура:   
- Оформить подписку  

Пользователь выбирает "Оформить подписку".

Бот:  Отлично! Давайте оформим подписку. Какой период вас интересует?  

Клавиатура:     
- 1 месяц  
- 3 месяца  
- 6 месяцев

## 2. Оформление подписки

### Диалог:  

Пользователь выбирает период подписки (например, "3 месяца").

Бот: Вы выбрали подписку на 3 месяца. Пожалуйста, выслите мне чек оплаты (картинку или PDF-файл).  
Пользователь отправляет чек.  
Бот: Спасибо! Ваш чек отправлен на проверку админу. Ожидайте подтверждения.  

Бот ждет подтверждения от админа.  
Если :

- Админ подтвердил:  
Бот: Оплата подтверждена! Ваша подписка активирована.  

- Админ отклонил:  
Бот: К сожалению, ваша оплата была отклонена. Пожалуйста, свяжитесь с поддержкой.  

## 3. Проверка платежа

### Диалог:  
Админ получает сообщение.  
Бот: Пользователь [Имя пользователя] оформил подписку. Чек: [чек]. Выберите действие: 

Клавиатура:  
- Подтвердить  
- Отклонить


Если админ выбирает: 

- "Подтвердить"  
Бот: Оплата подтверждена. Пользователь уведомлен.  
Если админ не отвечает в течение таймаута:  
Бот: Запрос передан свободному админу.  

- "Отклонить"  
Бот: Оплата отклонена. Пользователь уведомлен.


## 4. Когда подписка истекает

### Диалог:
Бот: Ваша подписка скоро истечет. Хотите продлить? 

Клавиатура:

- Да  
- Нет  

Если пользователь выбирает "Нет":  
Бот: Мы можем предложить вам скидку 10%. Хотите воспользоваться? 

Клавиатура:  
- Да  
- Нет  

Если пользователь выбирает "Да":  
Бот: Отлично! Давайте оформим подписку. (переход к сценарию оформления подписки)  

## 5. REST API

### Диалог:
При обновлении данных аккаунта:  
Бот: Данные вашего аккаунта были обновлены. Новые данные:  
- Email: new-account-email  
- Пароль: new-account-password

**Comment by Chamber6821** [comment]
Да, пойдет
