### ISSUE TITLE
Сделать реализацию `AdminFromUser` интерфейса `Admin`

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#14]
Нужно реализовать его и написать 1-3 теста с примерами использования

**Comment by gerushenka** [comment]
можешь объяснить подробней про то что нужно сделать ?

**Comment by gerushenka** [comment]
> Адаптер с `User` на `Admin`. Кстати, для ее написание необходимо пересмотреть метод `answer`, потому что `Message` не позволяет получить информацию от пользователя, а только отправить ее. Так же просто строка не подойдет, потому что пользователь может отправить нам файл, возможно стоит ввести некий тип `Answer`. Что бы точно это узнать, надо составить список способов по средству которых пользователь может дать ответ или по взаимодействовать в ботом.

export type Answer = Message | string | File
нормальный ли будет так сделать ?

**Comment by gerushenka** [comment]
AdminFromUser разве не должен апрувить просто платёж юзера??

**Comment by Chamber6821** [comment]
Admin апрувит платеж, но не говорит, как он это делает. А вот AdminFromUser подкапотом общается с админом, как с пользователем для того, что бы заапрувить оплату

**Comment by Chamber6821** [comment]
> export type Answer = Message | string | File нормальнo ли будет так сделать ?

Пользователь же может и по клаве тыкнуть. Я вот думаю, что у пользователя должны быть разные методы для ожидания разных его действий. Либо должен быть какой-то универсальный метод, а через декораторы ты настраиваешь чего ты ждешь. Может быть что-то такое

```ts
await (await user.reaction()).text()

await (await user.reaction()).button()

await (await user.reaction()).file()

await (await user.reaction()).image()
```

**Comment by Chamber6821** [comment]
Но таком подходе есть проблема с ожиданием разных реакций одновременно

**Comment by gerushenka** [comment]
так и что в итоге сделать

**Comment by Chamber6821** [comment]
Можно попробовать что-то вроде

```ts
type TextReactionStruct = {
  type: 'text',
  value: string
}

type FileReactionStruct = {
  type: 'file',
  value: ...
}

type ReactionStruct = TextReactionStruct | FileReactionStruct | ...

const variant: ReactionStruct = await new FilteredReaction(
  await user.reaction(),
  x => ['file', 'photo'].includes(x.type)
).asStruct()
```
