### ISSUE TITLE
Сделать реализацию `TextMessage` интерфейса `Message`

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#17]
Нужно реализовать его и написать 1-3 теста с примерами использования

**Comment by gerushenka** [comment]
по поводу интерфейса Message мы разве не делаем интерфейс Chat  с методами отправки текста, изображения, файла , а в Message только SendTo?

**Comment by Chamber6821** [comment]
Ну да. Только контент который будет отправлен - это и есть Message
