### ISSUE TITLE
Создать пустой проект

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#2]
Нужен пустой NodeJS проект на TypeScript (не JavaScript) с установленными пакетами:

- [Telegraf](https://www.npmjs.com/package/telegraf)
- [Express](https://www.npmjs.com/package/express)
- [Prisma](https://www.npmjs.com/package/prisma)

Так же нужно скопировать файд `.github/workflows/yougile-tasks.yml` из проекта [Kosox](https://github.com/Chamber6821/kosox-web) в тоже самое место этого проекта. Там лежат экшены для интеграции с нашим таск трекером

Еще в проекте должен быть `Dockerfile` по которому можно собрать образ микросервиса без зависимостей. [Пример](https://github.com/Chamber6821/kosox-web/blob/master/Dockerfile).

И `docker-compose.yml` с микросервисом и его базой данных. Нужно для тестирования и как пример настройки микросервиса. [Пример](https://github.com/Chamber6821/kosox-entry/blob/master/docker-compose.yml)

**Comment by gerushenka** [comment]
#5 
#4

**Comment by Chamber6821** [comment]
@gerushenka ок, я вижу, что ты не знаком с этими технологиями, я сам закрою эту задачу
