### ISSUE TITLE
Сделать реализацию `NumberPrice` интерфейса `Price`

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#22]
Нужно реализовать его и написать 1-3 теста с примерами использования

**Comment by gerushenka** [comment]
что должно быть в этом методе ?

**Comment by Chamber6821** [comment]
Это просто обёртка над `number`. Банально `amount: async () => x`

**Comment by gerushenka** [comment]
а как сделать тесты ?

**Comment by Chamber6821** [comment]
Рядом с тестируемым модулем кладешь файл `.test.ts`. Пример: хочешь протестировать `src/price/NumberPrice.ts`, создаешь файл `src/price/NumberPrice.test.ts` и в нем будешь писать тесты. А как писать тесты - гугли гайды по Jest
