### ISSUE TITLE
Сделать реализацию `SessionWithUpdateHandler` интерфейса `Session`

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/telegram-bot#24]
Нужно реализовать его и написать 1-3 теста с примерами использования

**Comment by gerushenka** [comment]
можешь объяснить подробней про то что нужно сделать ?

**Comment by Chamber6821** [comment]
Это сессия, которая вызывает переданный в конструкторе обработчик при обновлении аккаунта сессии. Предполагается, что в месте использования обработчик будет отправлять пользователю сообщение об обновлении данных аккаунта
